Change in LowPower.cpp
Scripts could not be compiled for Arduino MEGA. Error message from IDE:

D:\NewDokumenty\Arduino\libraries\AutomationShield\src\LowPower.cpp: In member function 'void LowPowerClass::disableBOD()':

D:\NewDokumenty\Arduino\libraries\AutomationShield\src\LowPower.cpp:99:17: error: 'BODS' was not declared in this scope

  MCUCR |= (1 << BODS)|(1 << BODSE);                         // Set brownout detection sleep (BODS) bit and brownout detection sleeep enable (BODSE) at the same time

                 ^~~~

D:\NewDokumenty\Arduino\libraries\AutomationShield\src\LowPower.cpp:99:17: note: suggested alternative: 'BORF'

  MCUCR |= (1 << BODS)|(1 << BODSE);                         // Set brownout detection sleep (BODS) bit and brownout detection sleeep enable (BODSE) at the same time

                 ^~~~

                 BORF

D:\NewDokumenty\Arduino\libraries\AutomationShield\src\LowPower.cpp:99:29: error: 'BODSE' was not declared in this scope

  MCUCR |= (1 << BODS)|(1 << BODSE);                         // Set brownout detection sleep (BODS) bit and brownout detection sleeep enable (BODSE) at the same time

                             ^~~~~

exit status 1
Nastala chyba pri kompilácii pre dosku Arduino Mega or Mega 2560.